name: Spring Security Core
desc: The Spring Security plugin simplifies the integration of Spring Security into GrailsÂ® framework
  applications.
coords: org.apache.grails:grails-spring-security
owner: Apache Software Foundation
vcs: https://github.com/apache/grails-spring-security
docs: https://apache.github.io/grails-spring-security/latest/core-plugin/guide/
maven-repo: https://repo1.maven.org/maven2
labels:
  - security
  - spring-security
licenses:
  - Apache-2.0
versions:
  - version: 7.0.0
    date: 2025-10-24T16:08:14Z
    grailsVersion: 7.0.0 > *
  - version: 7.0.0-RC2
    date: 2025-09-05T04:06:13Z
    grailsVersion: 7.0.0 > *
  - version: 7.0.0-M5
    date: 2025-07-24T02:13:05Z
    grailsVersion: 7.0.0 > *
  - version: 7.0.0-M4
    date: 2025-06-12T02:01:14Z
    grailsVersion: 7.0.0 > *
  - version: 7.0.0-M3
    date: 2025-03-05T21:12:40Z
    grailsVersion: 7.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 7.0.0-M1
    date: 2024-12-24T00:24:17Z
    grailsVersion: 6.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 6.1.2
    date: 2024-12-06T22:09:08Z
    grailsVersion: 6.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 6.1.1
    date: 2023-12-19T20:29:48Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 6.1.0
    date: 2023-11-07T10:44:11Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 6.0.3
    date: 2025-10-11T00:20:51Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 6.0.2
    date: 2025-10-11T00:20:51Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 6.0.1
    date: 2025-10-11T00:20:51Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 6.0.0
    date: 2025-10-11T00:20:51Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 5.3.0
    date: 2025-10-11T00:20:51Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 5.2.1
    date: 2025-10-11T00:20:51Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 5.2.0
    date: 2025-10-11T00:20:51Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 5.1.1
    date: 2025-10-11T00:20:51Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 5.1.0
    date: 2025-10-11T00:20:51Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 5.0.0
    date: 2025-10-11T00:20:51Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 5.0.0-RC1
    date: 2025-10-11T00:20:51Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 4.0.5
    date: 2022-11-14T05:03:43Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 4.0.4
    date: 2022-01-06T19:11:59Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 4.0.3
    date: 2021-02-24T05:38:51Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 4.0.2
    date: 2021-02-24T05:38:52Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 4.0.1
    date: 2021-02-24T05:38:53Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 4.0.0
    date: 2021-02-24T05:38:53Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 4.0.0.RC3
    date: 2021-02-24T05:38:53Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 4.0.0.RC2
    date: 2021-02-24T05:38:54Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 4.0.0.RC1
    date: 2021-02-24T05:38:54Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 4.0.0.M2
    date: 2021-02-24T05:38:55Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 4.0.0.M1
    date: 2021-02-24T05:38:54Z
    grailsVersion: 4.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.3.2
    date: 2022-11-18T12:38:05Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.3.1
    date: 2021-02-24T05:38:53Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.3.0
    date: 2021-02-24T05:38:53Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.2.3
    date: 2021-02-24T05:38:55Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.2.2
    date: 2021-02-24T05:38:55Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.2.1
    date: 2021-02-24T05:38:56Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.2.0
    date: 2021-02-24T05:38:56Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.2.0.M1
    date: 2021-02-24T05:38:56Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.1.2
    date: 2021-02-24T05:38:57Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.1.1
    date: 2021-02-24T05:38:57Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.1.0
    date: 2021-02-24T05:38:57Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.0.4
    date: 2021-02-24T05:38:58Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.0.3
    date: 2021-02-24T05:38:58Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.0.2
    date: 2021-02-24T05:38:59Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.0.1
    date: 2021-02-24T05:38:59Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.0.0
    date: 2021-02-24T05:38:59Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 3.0.0.M2
    date: 2021-02-24T05:38:58Z
    grailsVersion: 3.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/core
  - version: 2.0.0
    date: 2015-12-08T00:21:41Z
    grailsVersion: 2.3.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 2.0-RC6
    date: 2015-11-17T03:00:57Z
    grailsVersion: 2.3.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 2.0-RC5
    date: 2015-06-04T13:49:38Z
    grailsVersion: 2.3.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 2.0-RC4
    date: 2014-07-08T11:52:11Z
    grailsVersion: 2.3.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 2.0-RC3
    date: 2014-05-19T18:08:13Z
    grailsVersion: 2.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 2.0-RC2
    date: 2013-10-04T06:38:23Z
    grailsVersion: 2.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 2.0-RC1
    date: 2013-10-04T03:24:05Z
    grailsVersion: 2.0.0 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.2.7.4
    date: 2014-05-12T09:24:57Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.2.7.3
    date: 2012-05-22T07:26:50Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.2.7.2
    date: 2012-03-12T20:31:20Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.2.7.1
    date: 2012-03-12T20:31:42Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.2.7
    date: 2012-03-12T20:31:41Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.2.6
    date: 2012-03-12T20:31:41Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.2.5
    date: 2012-03-12T20:31:40Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.2.4
    date: 2012-03-12T20:31:40Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.2.3
    date: 2012-03-12T20:31:39Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.2.2
    date: 2012-03-12T20:31:39Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.2.1
    date: 2012-03-12T20:31:39Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: '1.2'
    date: 2012-03-12T20:31:39Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.1.3
    date: 2012-03-12T20:31:38Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.1.2
    date: 2012-03-12T20:31:38Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.1.1
    date: 2012-03-12T20:31:37Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: '1.1'
    date: 2012-03-12T20:31:37Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 1.0.1
    date: 2012-03-12T20:31:36Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: '1.0'
    date: 2012-03-12T20:31:36Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 0.4.2
    date: 2012-03-12T20:31:35Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 0.4.1
    date: 2012-03-12T20:31:35Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: '0.4'
    date: 2012-03-12T20:31:34Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: 0.3.1
    date: 2012-03-12T20:31:34Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: '0.3'
    date: 2012-03-12T20:31:34Z
    grailsVersion: 1.2.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: '0.2'
    date: 2012-03-12T20:31:33Z
    grailsVersion: 1.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
  - version: '0.1'
    date: 2012-03-12T20:31:33Z
    grailsVersion: 1.2 > *
    coords: org.grails.plugins:spring-security-core
    maven-repo: https://repo.grails.org/plugins
